FROM rust:latest AS build
WORKDIR /app

RUN rustup target add x86_64-unknown-linux-musl

COPY core/sid/Cargo.toml core/sid/Cargo.lock ./
RUN mkdir -p src && echo 'fn main() {}' > src/main.rs
RUN cargo build --release --target x86_64-unknown-linux-musl

COPY core/sid/src ./src
RUN touch src/main.rs
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM scratch
COPY --from=build /app/target/x86_64-unknown-linux-musl/release/vtfk-sid /vtfk-sid
ENTRYPOINT ["/vtfk-sid"]